# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3776d854e454523f3ee881aae87f477c4f320dd84601316f385b1961a305c47a8e79efa1e784f46abf5ef7f2f20c4a4a6fef9a28f9f438df622a59c41132ecdb

test:
  secret_key_base: b63fdb33d1254103dd0998bb3aeaab4c457557a80f28ddd8fc2633452976e4764c60d43a7722e2cc412dab39a239b015e260fc2c6ebf76ea394a5f43dc44a58b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
